export enum NotificationType {
  COMMENT = 'COMMENT', 
  NEW_POST = 'NEW_POST', 
  REACTION = 'REACTION',
  GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST',
  GROUP_JOIN_REQUEST_ACCEPT = 'GROUP_JOIN_REQUEST_ACCEPT',
  FRIEND_REQUEST_ACCEPT = 'FRIEND_REQUEST_ACCEPT',
  FRIEND_REQUEST = 'FRIEND_REQUEST'
}
